trigger: none
pool: umesh-the-agent

parameters:
- name: environment # Required as first property.
  displayName: select environment # Human-readable name for the parameter.
  type: string
  values:
  - dev
  - prod

# variables:
# - name: string # Required as first property. Variable name.
#   value: string # Variable value.
  

jobs:
  - job: terraform
    steps:
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        backendServiceArm: 'service_connection_norway_client2'
        backendAzureRmOverrideSubscriptionID: 'eab63ffb-bf3a-4d0f-b9f7-d3c577ca3158'
        backendAzureRmResourceGroupName: 'rg_servicetest'
        backendAzureRmStorageAccountName: 'testrg0004storageaccount'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'dev.terraform.tfstate'


    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'service_connection_norway_client2'
        environmentAzureRmOverrideSubscriptionID: 'eab63ffb-bf3a-4d0f-b9f7-d3c577ca3158'

    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'service_connection_norway_client2'
        environmentAzureRmOverrideSubscriptionID: 'eab63ffb-bf3a-4d0f-b9f7-d3c577ca3158'